config/routes.rb
Rails.application.routes.draw do
 root "my_pieces#index"
 resources :my_lines, as: "lines"
 resources :my_sections, as: "sections"
 resources :my_pieces, as: "pieces"
end

app/models/line.rb
class Line < ActiveRecord::Base
end

app/models/piece.rb
class Piece < ActiveRecord::Base
end

app/models/section.rb
class Section < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/my_lines_controller.rb
class MyLinesController < ApplicationController

  def index
    @line = Line.all
  end

  def show
    @line = Line.find(params[:id])
  end

  def edit
     @line = Line.find(params[:id])
  end

  def update
    @line = Line.find(params[:id])
    @line.update(line_params)
    redirect_to @line
  end

  def new
    @line = Line.new
  end

  def create
    @line = Line.new(line_params)
    @line.save
    redirect_to @line
  end

private

  def line_params
    params.require(:line).permit(:content)
  end

end

app/controllers/my_pieces_controller.rb
class MyPiecesController < ApplicationController

  def index
    @piece = Piece.all
  end

  def show
    @piece = Piece.find(params[:id])
  end

  def edit
    @piece = Piece.find(params[:id])
  end

  def update
    @piece = Piece.find(params[:id])
    @piece.update(piece_params)
    redirect_to @piece
  end

  def new
    @piece = Piece.new
  end

  def create
    @piece = Piece.new(piece_params)
    @piece.save
    redirect_to @piece
  end

private

  def piece_params
    params.require(:piece).permit(:title, :content)
  end

end

app/controllers/my_sections_controller.rb
class MySectionsController < ApplicationController

  def index
    @section = Section.all
  end

  def show
    @section = Section.find(params[:id])
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    @section.update(section_params)
    redirect_to @section
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)
    @section.save
    redirect_to @section
  end

private

  def section_params
    params.require(:section).permit(:content)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_lines_helper.rb
module MyLinesHelper
end

app/helpers/my_pieces_helper.rb
module MyPiecesHelper
end

app/helpers/my_sections_helper.rb
module MySectionsHelper
end

app/views/application/_footer.html.erb
<footer>
  <p>Copyright &copy; 2016
    <%= link_to 'Snydes Designs', 'http://snydesdesigns.com' %>
  </p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LyricApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>
  <%= link_to("My Lines", lines_path)%>
  <%= link_to("My Sections", sections_path)%>
  <%= link_to("My Pieces", pieces_path)%>
</header>
<body>

<%= yield %>

</body>
<%= render 'footer' %>
</html>

app/views/my_lines/_form.html.erb
<%= form_for(@line) do |f| %>
<p>
  <%= f.label :content %><br/>
  <%= f.text_field :content, autofocus: true %>
</p>
<p>
  <%= f.submit %>
  <%= link_to "Cancel", lines_path %>
</p>
<% end %>

app/views/my_lines/edit.html.erb
<h1>Editing Line: <%= @line.content %></h1>
<%= render 'form'  %>

app/views/my_lines/index.html.erb
<h1>My Lines</h1>
<h3><%= pluralize(@line.size, 'Line') %></h3>
<ul>
  <% @line.each do |line| %>
  <li class="line"><%= line.content %></li>
  <% end %>
</ul>
<%= link_to("New Line", new_line_path) %>

app/views/my_lines/new.html.erb
<h1>Create a New Line</h1>
<%= render 'form' %>

app/views/my_lines/show.html.erb
<p><%= @line.content %></p>
<%= link_to("All Lines", line_path) %>
<%= link_to("Edit", edit_line_path(@line)) %>

app/views/my_pieces/_form.html.erb
<%= form_for (@piece) do |f| %>
<p>
  <%= f.label :title %><br/>
  <%= f.text_field :title, autofocus: true %>
  <%= f.label :content %><br/>
  <%= f.text_field :content %>
</p>
<p>
  <%= f.submit %>
  <%= link_to "Cancel", pieces_path %>
</p>
<% end %>

app/views/my_pieces/edit.html.erb
<h1>Editing Piece: <%= @piece.title %></h1>
<%= render 'form' %>

app/views/my_pieces/index.html.erb
<h1>My Creative Pieces</h1>
<h3><%= pluralize(@piece.size, 'Piece') %></h3>
<ul>
  <% @piece.each do |piece| %>
  <li>
    <strong><%= piece.title %></strong><br/>
    <%= piece.content %><%= " " %><%= link_to("View this Piece", piece_path(piece))%></li>
  <% end %>
</ul>
<%= link_to("New Piece", new_piece_path) %>

app/views/my_pieces/new.html.erb
<h1>Create a New Piece</h1>
<%= render 'form' %>

app/views/my_pieces/show.html.erb
<h1><%= @piece.title %></h1>
<p><%= @piece.content %></p>

<%= link_to("All Pieces", piece_path) %>
<%= link_to("Edit", edit_piece_path(@piece)) %>

app/views/my_sections/_form.html.erb
<%= form_for(@section) do |f| %>
<p>
  <%= f.label :content %><br/>
  <%= f.text_area :content, autofocus: true %>
</p>
<p>
  <%= f.submit %>
  <%= link_to "Cancel", sections_path %>
</p>
<% end %>

app/views/my_sections/edit.html.erb
<h1>Editing Section: <%= @section.content %></h1>
<%= render 'form' %>

app/views/my_sections/index.html.erb
<h1>My Sections</h1>
<h3><%= pluralize(@section.size, 'Section') %></h3>
<ul>
  <% @section.each do |section| %>
  <li class="line"><%= section.content %></li>
  <% end %>
</ul>
<%= link_to("New Section", new_section_path) %>

app/views/my_sections/new.html.erb
<h1>Create a New Section</h1>
<%= render 'form' %>

app/views/my_sections/show.html.erb
<p><%= @section.content %></p>
<%= link_to("All Sections", section_path) %>
<%= link_to("Edit", edit_section_path(@section)) %>